apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: php-app
  app.kubernetes.io/part-of: php-app
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
