apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: php-app-dev2
commonLabels:
  environment: dev2
resources:
  - ../../base
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
patchesStrategicMerge:
  - patches/deployment.yaml
  - patches/configmap.yaml
