apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: php
          env:
            - name: PHP_DISPLAY_ERRORS
              value: "1"
          volumeMounts:
            - name: dev2-php-app-volume
              mountPath: /var/log/php-app
              subPath: dev2
      volumes:
        - name: dev2-php-app-volume
          persistentVolumeClaim:
            claimName: php-app-dev2-pvc
