apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: php
          env:
            - name: PHP_DISPLAY_ERRORS
              value: "1"
          volumeMounts:
            - name: dev1-php-app-logs
              mountPath: /var/log/php-app
              subPath: dev1
      volumes:
        - name: dev1-php-app-logs
          persistentVolumeClaim:
            claimName: php-app-logs
